### ISSUE TITLE
Erro na instalação - $ make db-setup

### ISSUE THREAD

**Issue by ronenfilho** [libercapital/dados_publicos_cnpj_receita_federal#20]
Olá, 
erro durante a instalação, na etapa de execução do comando: **$ make db-setup**

Vide imagem: 
![image](https://user-images.githubusercontent.com/7609445/222907853-715204d3-f8c5-4141-a07d-3781b1ae72a4.png)

Parece que a imagem:     image: dados_publicos:1.0
não está disponível.

**Comment by JeanBarbosa** [comment]
> Olá, erro durante a instalação, na etapa de execução do comando: **$ make db-setup**
> 
> Vide imagem: ![image](https://user-images.githubusercontent.com/7609445/222907853-715204d3-f8c5-4141-a07d-3781b1ae72a4.png)
> 
> Parece que a imagem: image: dados_publicos:1.0 não está disponível.

No arquivo do docker-compose.yaml tem um variavel 'PWD' que seria o path do projeto... por algum motivo no seu ambiente nao está carregando... ja tentou setar manualmente esse caminho?
