### ISSUE TITLE
Link de recurso não existe mais

### ISSUE THREAD

**Issue by mpereiradev** [libercapital/dados_publicos_cnpj_receita_federal#22]
O link do recurso:
https://dados.gov.br/dados/conjuntos-dados/cadastro-nacional-da-pessoa-juridica-cnpj

Não existe mais e redireciona para esse link:
https://dados.gov.br/error

Isso acaba quebrando o make io-download-and-unzip

/app/src/io/get_files_dict.py:71: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  soup_tax_regime = BeautifulSoup(page_tax_regime.text, 'html.parser')
Traceback (most recent call last):
  File "src/io/download.py", line 97, in <module>
    main()
  File "src/io/download.py", line 17, in main
    dict_files_dict = get_files_dict()
  File "/app/src/io/get_files_dict.py", line 74, in main
    rows_tax_regime = table_tax_regime.find_all('tr')
AttributeError: 'NoneType' object has no attribute 'find_all'
make: *** [io-download-and-unzip] Error 1

**Comment by JeanBarbosa** [comment]
O link do recurso agora é: 
https://dados.gov.br/dados/conjuntos-dados/cadastro-nacional-da-pessoa-juridica---cnpj

Creio que o error se refere a outro link...
http://200.152.38.155/CNPJ/anual  que agora é http://200.152.38.155/CNPJ/regime_tributario/

src/io/get_files_dict.py
```
   # get page of tax regime
    page_tax_regime = requests.get(
        f"{CORE_URL_FILES}/anual", headers=HEADERS) 
``` 
isso deve resolver

```  
  # get page of tax regime
    page_tax_regime = requests.get(
        f"{CORE_URL_FILES}/regime_tributario", headers=HEADERS) 
```
