### ISSUE TITLE
Erro na execução do "make engine-company"

### ISSUE THREAD

**Issue by tuliovileladias** [libercapital/dados_publicos_cnpj_receita_federal#24]
Em uma das últimas etapas, estou obtendo um erro. 

Alguém passou por isso?

Vou descrever todo log desde a execução até o erro:

$ make engine-company
'
---------------------------------------
docker-compose up -d
postgres is up-to-date
Starting app ... done

compose-up run app container & [ENGINE COMPANY]
Creating dados_publicos_cnpj_receita_federal_app_run ... done
creating dict files url
ref date will be: '2024-01-16' with 37 out of 37 (100.0%)
No pk found on: 'rf_company'
Pk not found on: 'rf_company'
No indexes found on: 'rf_company'
Can't delete 'ix_rf_company_cnpj_root' on :'rf_company' --> index does not exists
No indexes found on: 'rf_company'
Can't delete 'ix_rf_company_cnpj' on :'rf_company' --> index does not exists
[ 1/9] Getting file K3241.K03200Y1.D40113.ESTABELE
                2024-01-20 20:49:49  | sending to db
ERROR: 137
make: *** [Makefile:147: engine-company] Error 137
root@amplisalev1:~/dados_publicos_cnpj_receita_federal# ^C
root@amplisalev1:~/dados_publicos_cnpj_receita_federal#
'

**Comment by Robso-creator** [comment]
Parece ser algum problema na configuração do banco de dados, conseguiu resolver?
