### ISSUE TITLE
Como acessar o banco

### ISSUE THREAD

**Issue by GabrelCarvalho** [libercapital/dados_publicos_cnpj_receita_federal#26]
Olá, pessoal!
Sou bastante leigo no universo da programação, mas devido a projetos pessoais tenho feito uso. O processo é bastante lento, pois executo enquanto aprendo - demorei duas semanas para conseguir configurar o wsl ubuntu e o docker em um hd externo.
Enfim. Executei todos os comandos indicados nesse repositório, mas a minha dúvida é:
Como faço para acessar o banco e realizar consultas SQL nele? Não sei como me conectar a esse banco criado pelos comandos mencionado aqui no git.
Espero que alguém possa ajudar e desde já agradeço.

**Comment by Robso-creator** [comment]
@GabrelCarvalho no readme tem uma parte explicando como se conectar ao banco, bem abaixo da configuração de conexão no `.env`

![image](https://github.com/user-attachments/assets/0918bb01-1e30-42cd-b2b1-7ccdcf309521)

voce vai precisar de um **SGBD**, como o DBEAVER, para se conectar ao banco
link para um artigo sobre: https://alexdepaula18.medium.com/conectando-no-banco-de-dados-postgresql-utilizando-dbeaver-community-1275f4c9bcba

espero que te ajude!
